version: 0.1

phases:
  build:
    commands:
      - npm install
      - npm run webpack

artifacts:
  files:
    - index.html
    - favicon.ico
    - Declan_Brady_CV_2014.doc
    - styles/main.css
    - images/*
    - dist/bundle.js
